### ISSUE TITLE
Different instances of google-maps-api with different specified libraries causes conflicts

### ISSUE THREAD

**Issue by levitanong** [GoogleWebComponents/google-apis#22]
Somewhat related to #20.

Especially problematic with `<google-map>`, which has its own import of `<google-maps-api>` with hard-coded `libraries="places"`. If on the same page you have a `<google-maps-api>` with `libraries="places,geometry"`, two things happen:

1. We get an error: `You have included the Google Maps API multiple times on this page. This may cause unexpected errors.` This suggests that core-shared-library treats these two as separate, which causes the google warning.

2. When trying to use methods from one instance of the API on the other (like the map) things get weird. 
For example, when trying to render a polyline from an encoded string (requires the geometry library) onto a `<google-map map="{{gmap}}">`, gmap is not considered by the geometry library as type Map. 
However, a map created manually without the `<google-map>` (and therefore doesn't use its own `<google-maps-api>`) works just fine.
If I change the `google-maps-api.html` default value for `libraries` to `"places,geometry`", the geometry library works properly when used with `google-map`.

**Comment by brendankenny** [comment]
(merging from #57)

<rambling-background>Due to the way the Maps API loads [libraries](https://developers.google.com/maps/documentation/javascript/libraries) (designed in the ancient days of ~2008) you have to load all the libraries you'll need on first load and can't load more libraries later. You also need to make sure the API is only loaded once on each page.

The second problem is taken care of by `<google-maps-api>` but the first means that every other element that uses it needs to specify the same set of libraries as the rest for them to work on the same page together. This can be problematic if you're trying to make a SPA and have a need for different libraries in different parts of your app, or if you don't even realize an element you're using contains a `<google-maps-api>` and so needs a `libraries` property properly set. We leave it up to the end developer to coordinate this (see e.g. https://github.com/GoogleWebComponents/google-streetview-pano/issues/15). Once you know the problem exists, it's easy to diagnose and fix, but it's annoying.</rambling-background>

To eliminate these problems, I propose we always load all four libraries whenever the Maps API is loaded and eliminate the `libraries` property on all `google-map-*` elements. Configuration gets simpler, you don't have to repeat yourself over and over to use the exact same libraries you already loaded, and we eliminate a class of bugs. Boom.

Downsides:
- libraries are loaded as separate JS files, requiring four more network requests *dependent on the bootstrap script loading and executing*
- some amount of parse and initialization time for the libraries, even if unused (beyond what the JS engine has to do because of the way the Google Maps loader works)

Why the downsides aren't so bad:
- total download size of the four libraries is ~5.5KB with gzip (~9.5KB after unzip)
- there are already 15 scripts loaded with a vanilla Maps API load that we weren't worrying about before :)
- the library script downloads are launched immediately by the bootstrap script, in parallel to the `main.js` script file
- Maps API files are served with QUIC or HTTP2 or SPDY where available, so extra requests are multiplexed over an already open connection

Any possible network performance problem should be fixed at the browser/Maps API/serving infrastructure levels anyways. We shouldn't burden all the `google-map-*` components with this additional API complexity.

As Eric notes above, the suggestion in this thread will not work because of the temporal aspect of the problem: the only union of libraries that will include all possible libraries needed by elements that could be added to the page in the future is the set of all libraries. Might as well load all of them :)
